[Logging]Add Logging Module
PaddlePaddle/ERNIE-SDK pull request #70
Opened 2023-11-14 06:39 UTC by Southpika

已添加logging模块，erniebot-agent/tests/integration_tests/agents/test_functional_agent.py文件测试通过
@Bobholamovic @juncaipeng @sijunhe

2023-11-14 14:51 UTC, Bobholamovic requested changes
当前的日志方案可以让`LoggingHandler`输出带有颜色的美观日志。不过，我认为当前方案存在如下局限性：

1. 每个要打印日志的模块都需要单独实例化`AgentLogger`，过多的实例将造成额外的开销，而实际上只是为了实现日志功能的话并不需要如此多实例。
2. `AgentLogger`所依赖的底层logger是singleton，而`AgentLogger`本身不是。当前的未加锁实现将会导致多线程环境下出现race condition。
3. 由于未遵守logging标准库的开发规范，在与其它库协作的时候可能遇到问题。例如，用户在一个应用中同时使用erniebot-agent与requests（用到了urllib3）。用户使用logging库的标准配置方式为`urllib3`配置日志等级和输出格式：
    ```python
    import erniebot_agent
    import urllib3
    import logging
    logging.basicConfig(level="DEBUG", format="%(message)s")
    ...
    ```
在程序执行时，erniebot-agent的logger会将每条日志打印两次，一次是erniebot-agent风格（`"%(levelname)s - %(message)s"`），一次是上述代码设置的`"%(message)s"`风格。

为了克服上述局限性，我建议修改logging方案。首先，logging模块应该为其它模块提供便利而高效的日志接口；其次，作为library，我们的logging功能不用太特化，这样可以给application developer预留更大的可定制空间。一些详细一点的建议如下：

1. logging模块默认不添加handler（Python3.8以上logging标准库的默认行为是：不添加handler的logger相当于只有一个`StreamHandler`，只打印`WARNING`及以上级别的日志）。
2. 用户如果需要低于`WARNING`级别的日志，例如看到`logger.info`的输出结果，则自行在application代码中使用`logging.basicConfig`等方式配置。不过，为了便利用户使用，我们的logging模块可以提供一个基本的config接口，用于设置日志等级（使用内置的带有颜色的日志风格）。另外一个可以实现的功能是根据环境变量（例如`EB_AGENT_LOGGING_LEVEL`）来自动配置logger，可参考[OpenAI Python Library的日志方案](https://github.com/openai/openai-python/blob/65e29a2efa455a06deb59e243f27796c4ca2254c/src/openai/_utils/_logs.py#L17)。
3. 根据Python logging标准库惯例，将以package name命名的logger作为library root logger，各模块写日志时通过`logging.getLogger(__name__)`获取logger。另一种可选方案是集中式管理，即在logging模块中实现一个singleton logger并对外暴露（或者对外暴露`debug`、`info`等函数），其余模块import logging中的logger或函数记录日志。

2023-11-14 14:51 UTC, Bobholamovic commented on erniebot-agent/erniebot_agent/agents/logging_config.py
> +        "DEBUG": "\033[95m",  # Purple
使用了ANSI escape sequences，可能需要考虑平台兼容性问题

2023-11-14 14:51 UTC, Bobholamovic commented on erniebot-agent/erniebot_agent/agents/logging_config.py
> +        """
docstring需要使用英文书写

2023-11-14 14:51 UTC, Bobholamovic commented on erniebot-agent/erniebot_agent/agents/callback/handlers/logging_handler.py
> +class LoggingHandler(CallbackHandler, AgentLogger):
`LoggingHandler`和`AgentLogger`应该不满足is-a关系，而是has-a关系，因此建议考虑这两个类之间为组合关系。

2023-11-14 14:51 UTC, Bobholamovic commented on erniebot-agent/erniebot_agent/agents/logging_config.py
> +        # 删除之前的handler以免重复输出
comment也尽可能使用英文书写～

2023-11-14 14:51 UTC, Bobholamovic commented on erniebot-agent/erniebot_agent/agents/logging_config.py
> +        self.logger.addHandler(logging.NullHandler())
前面已经加了handler，这里再添加`NullHandler`看起来没有必要了，可以去除

2023-11-14 14:51 UTC, Bobholamovic commented on erniebot-agent/erniebot_agent/agents/logging_config.py
> +        self.logger = logging.getLogger(name if name else "Agent Logger")
根据logging标准库的典型使用例子，默认logger名称最好是package的名字

2023-11-14 14:51 UTC, Bobholamovic commented on erniebot-agent/erniebot_agent/agents/logging_config.py
> +class AgentLogger(object):
我们的logger不止用在agent里，这个名字可能不太合适

2023-11-16 11:28 UTC, Southpika commented
> 当前的日志方案可以让`LoggingHandler`输出带有颜色的美观日志。不过，我认为当前方案存在如下局限性：
> 
> 1. 每个要打印日志的模块都需要单独实例化`AgentLogger`，过多的实例将造成额外的开销，而实际上只是为了实现日志功能的话并不需要如此多实例。
> 2. `AgentLogger`所依赖的底层logger是singleton，而`AgentLogger`本身不是。当前的未加锁实现将会导致多线程环境下出现race condition。
> 3. 由于未遵守logging标准库的开发规范，在与其它库协作的时候可能遇到问题。例如，用户在一个应用中同时使用erniebot-agent与requests（用到了urllib3）。用户使用logging库的标准配置方式为`urllib3`配置日志等级和输出格式：
>    ```python
>    import erniebot_agent
>    import urllib3
>    import logging
>    logging.basicConfig(level="DEBUG", format="%(message)s")
>    ...
>    ```
> 
> 在程序执行时，erniebot-agent的logger会将每条日志打印两次，一次是erniebot-agent风格（`"%(levelname)s - %(message)s"`），一次是上述代码设置的`"%(message)s"`风格。
> 
> 为了克服上述局限性，我建议修改logging方案。首先，logging模块应该为其它模块提供便利而高效的日志接口；其次，作为library，我们的logging功能不用太特化，这样可以给application developer预留更大的可定制空间。一些详细一点的建议如下：
> 
> 1. logging模块默认不添加handler（Python3.8以上logging标准库的默认行为是：不添加handler的logger相当于只有一个`StreamHandler`，只打印`WARNING`及以上级别的日志）。
> 2. 用户如果需要低于`WARNING`级别的日志，例如看到`logger.info`的输出结果，则自行在application代码中使用`logging.basicConfig`等方式配置。不过，为了便利用户使用，我们的logging模块可以提供一个基本的config接口，用于设置日志等级（使用内置的带有颜色的日志风格）。另外一个可以实现的功能是根据环境变量（例如`EB_AGENT_LOGGING_LEVEL`）来自动配置logger，可参考[OpenAI Python Library的日志方案](https://github.com/openai/openai-python/blob/65e29a2efa455a06deb59e243f27796c4ca2254c/src/openai/_utils/_logs.py#L17)。
> 3. 根据Python logging标准库惯例，将以package name命名的logger作为library root logger，各模块写日志时通过`logging.getLogger(__name__)`获取logger。另一种可选方案是集中式管理，即在logging模块中实现一个singleton logger并对外暴露（或者对外暴露`debug`、`info`等函数），其余模块import logging中的logger或函数记录日志。



> 当前的日志方案可以让`LoggingHandler`输出带有颜色的美观日志。不过，我认为当前方案存在如下局限性：
> 
> 1. 每个要打印日志的模块都需要单独实例化`AgentLogger`，过多的实例将造成额外的开销，而实际上只是为了实现日志功能的话并不需要如此多实例。
> 2. `AgentLogger`所依赖的底层logger是singleton，而`AgentLogger`本身不是。当前的未加锁实现将会导致多线程环境下出现race condition。
> 3. 由于未遵守logging标准库的开发规范，在与其它库协作的时候可能遇到问题。例如，用户在一个应用中同时使用erniebot-agent与requests（用到了urllib3）。用户使用logging库的标准配置方式为`urllib3`配置日志等级和输出格式：
>    ```python
>    import erniebot_agent
>    import urllib3
>    import logging
>    logging.basicConfig(level="DEBUG", format="%(message)s")
>    ...
>    ```
> 
> 在程序执行时，erniebot-agent的logger会将每条日志打印两次，一次是erniebot-agent风格（`"%(levelname)s - %(message)s"`），一次是上述代码设置的`"%(message)s"`风格。
> 
> 为了克服上述局限性，我建议修改logging方案。首先，logging模块应该为其它模块提供便利而高效的日志接口；其次，作为library，我们的logging功能不用太特化，这样可以给application developer预留更大的可定制空间。一些详细一点的建议如下：
> 
> 1. logging模块默认不添加handler（Python3.8以上logging标准库的默认行为是：不添加handler的logger相当于只有一个`StreamHandler`，只打印`WARNING`及以上级别的日志）。
> 2. 用户如果需要低于`WARNING`级别的日志，例如看到`logger.info`的输出结果，则自行在application代码中使用`logging.basicConfig`等方式配置。不过，为了便利用户使用，我们的logging模块可以提供一个基本的config接口，用于设置日志等级（使用内置的带有颜色的日志风格）。另外一个可以实现的功能是根据环境变量（例如`EB_AGENT_LOGGING_LEVEL`）来自动配置logger，可参考[OpenAI Python Library的日志方案](https://github.com/openai/openai-python/blob/65e29a2efa455a06deb59e243f27796c4ca2254c/src/openai/_utils/_logs.py#L17)。
> 3. 根据Python logging标准库惯例，将以package name命名的logger作为library root logger，各模块写日志时通过`logging.getLogger(__name__)`获取logger。另一种可选方案是集中式管理，即在logging模块中实现一个singleton logger并对外暴露（或者对外暴露`debug`、`info`等函数），其余模块import logging中的logger或函数记录日志。

已修改方案为初始实例化时实例化一个库logger供其他地方调用，在环境变量中配置1.logging显示层级以及2.是否需要按库默认显示方法来进行显示，若其他地方需调用，可直接使用erniebot_agent.logger直接使用。

TODO: ANSI的兼容问题暂未考虑，因linux系统下兼容，主要可能为windows不兼容，可能需要windows电脑配合测试

烦请review～
@Bobholamovic @juncaipeng @sijunhe

2023-11-17 09:08 UTC, Bobholamovic commented on erniebot-agent/erniebot_agent/agents/callback/handlers/logging_handler.py
> +    def agent_info(self, msg: str, *args, level="Run", state="Start", **kwargs) -> None:
此处参数默认值无意义，建议改为`def agent_info(self, msg: str, *args, level, state, **kwargs)`

2023-11-17 09:08 UTC, Bobholamovic commented on erniebot-agent/erniebot_agent/agents/callback/handlers/logging_handler.py
> +        self.logger.error("[LLM][Error] %s", error)
这个是否也需要设置`agent_error`方法？

2023-11-17 10:13 UTC, Bobholamovic approved these changes
LGTM

2023-11-17 10:14 UTC, merged